name: Publish Python Package

on:
  push:
    tags:
      - "*"

jobs:
  publish-python-package:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install build dependencies
        run: |
          ./ci/linux/create_venv.sh
          ./ci/linux/install_dependencies.sh

      - name: Build package
        run: |
          ./ci/linux/build_python_package.sh

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
